name: Automerge Exercism Solutions

on:
  pull_request:

  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]' || 
      github.actor == 'exercism-solutions-syncer[bot]'
    steps:
      - name: Automerge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge "$PR_URL" --auto --merge
